device: 'cuda:0'
seed: 42

model:
  type: DeltaMapper
  module: src.models.delta_edit
  params: {}

data:
  type: TrainDeltaFFHQ
  module: src.datasets
  params:
    path_to_w_latents: "/workspace/data/wspace_ffhq_feat.npy"
    path_to_s_latents: "/workspace/data/sspace_ffhq_feat.npy"
    path_to_c_latents: "/workspace/data/cspace_ffhq_feat.npy"
    path_to_noise_w_latents: "/workspace/data/wspace_noise_feat.npy"
    path_to_noise_s_latents: "/workspace/data/sspace_noise_feat.npy"
    path_to_noise_c_latents: "/workspace/data/cspace_noise_feat.npy"

  batch_size: 4096
  num_workers: 5

optimizer:
  type: Adam
  module: torch.optim
  params:
    lr: 0.5

trainer:
  type: DeltaEditTrainer
  module: src.trainers
  params:
    n_epochs: 300
    l2_lambda: 1.0
    cos_lambda: 1.0
    log_step: 200
    save_dir: /workspace/saved/training_logs
    save_every: 50
    wandb_project: 'semantic-editing'
    wandb_run_name: 'DeltaEdit_baseline_training2'

resume: False
